# ============================================
# Loki Configuration
# ============================================

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s

memberlist:
  join_members:
    - loki:7946
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 1s
  gossip_nodes: 2
  left_ingesters_timeout: 5m
  dead_node_timeout: 5m

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
      heartbeat_timeout: 1m
  chunk_idle_period: 3m
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
  flushing_timeout: 1m
  concurrent_flushes: 16

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit_per_query: 5000
  max_cache_freshness_per_query: 10m
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB

chunk_store_config:
  max_look_back_period: 72h
  chunk_cache:
    enable_fifocache: true
    fifocache:
      size: 500MB
      ttl: 1h
      eviction_policy: lru

querier:
  engine:
    max_concurrent: 16
    timeout: 5m
  query_ingesters_within: 15m
  tail_max_duration: 1h

query_scheduler:
  max_outstanding_requests_per_tenant: 100

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 3

storage_config:
  filesystem:
    directory: /loki/chunks
  bolt:
    directory: /loki/index
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

tracing:
  enabled: false
